runtime: python37
entrypoint: streamlit run document_parse.py
env: standard
service: docsparser
instance_class: F2

automatic_scaling:
  max_instances: 5
  min_instances: 1
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.6

handlers:
- url: /.*
  script: auto
  secure: always
